package es.ramondin.lanzadoraplicaciones.model.views.client;

import es.ramondin.lanzadoraplicaciones.model.views.common.TParametrosVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 15:01:00 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TParametrosVOClient extends ViewUsageImpl implements TParametrosVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TParametrosVOClient() {
    }

    public String getValorParametro(String parametro) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorParametro",new String [] {"java.lang.String"},new Object[] {parametro});
        return (String)_ret;
    }
}
