package es.ramondin.lanzadoraplicaciones.model.views.client;

import es.ramondin.lanzadoraplicaciones.model.views.common.TSegSesionesVO;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 03 11:21:29 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegSesionesVOClient extends ViewUsageImpl implements TSegSesionesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TSegSesionesVOClient() {
    }

    public void actualizaTablaSesiones(Boolean crearRegistro, String idSesion,
                                       BigDecimal idUsuario,
                                       String codUsuario) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"actualizaTablaSesiones",new String [] {"java.lang.Boolean","java.lang.String","java.math.BigDecimal","java.lang.String"},new Object[] {crearRegistro, idSesion, idUsuario, codUsuario});
        return;
    }

    public Boolean existeIdSesion(String idSesion) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"existeIdSesion",new String [] {"java.lang.String"},new Object[] {idSesion});
        return (Boolean)_ret;
    }
}
