package es.ramondin.lanzadoraplicaciones.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 15:01:00 CEST 2014
// ---------------------------------------------------------------------
public interface TParametrosVO extends ViewObject {
    String getValorParametro(String parametro);
}
