package es.ramondin.lanzadoraplicaciones.model.views.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 03 11:21:29 CEST 2014
// ---------------------------------------------------------------------
public interface TSegSesionesVO extends ViewObject {
    void actualizaTablaSesiones(Boolean crearRegistro, String idSesion,
                                BigDecimal idUsuario, String codUsuario);

    Boolean existeIdSesion(String idSesion);
}
