package es.ramondin.lanzadoraplicaciones.model.views.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 08:22:45 CEST 2014
// ---------------------------------------------------------------------
public interface TSegUsuarioVO extends ViewObject {
    BigDecimal getIdUsuario(String codUsuario);

    BigDecimal getIdGrupo(String codUsuario);

    String getNombreUsuario(String codUsuario);
}
