package es.ramondin.lanzadoraplicaciones.model.views;

import es.ramondin.lanzadoraplicaciones.model.views.common.TParametrosVO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 14:59:21 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TParametrosVOImpl extends ViewObjectImpl implements TParametrosVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TParametrosVOImpl() {
    }
    
    public String getValorParametro(String parametro) {
        String res = null;
        
        this.setWhereClauseParam(0, parametro);
        this.executeQuery();
        
        Row rowTParametrosVO = this.first();
        
        if (rowTParametrosVO != null)
            res = (String)rowTParametrosVO.getAttribute(TParametrosVORowImpl.VALOR);
        
        return res;
    }
}
