package es.ramondin.lanzadoraplicaciones.model.views;


import es.ramondin.lanzadoraplicaciones.model.views.common.TSegSesionesVO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 03 10:47:49 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegSesionesVOImpl extends ViewObjectImpl implements TSegSesionesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TSegSesionesVOImpl() {
    }
    
    public Boolean existeIdSesion(String idSesion) {
        Boolean res = false;
        
        this.setWhereClauseParam(0, idSesion);
        this.executeQuery();
        
        if (this.getRowSet().getRowCount() > 0)
            res = true;
        
        return res;
    }
    
    public void actualizaTablaSesiones(Boolean crearRegistro, String idSesion, BigDecimal idUsuario, String codUsuario) {
        Row rowTSegSesionesVO = null;
        
        if (crearRegistro) {
            rowTSegSesionesVO = this.createRow();

            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.IDSESION, idSesion);
            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.IDUSUARIO, idUsuario);
            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.CODUSUARIO, codUsuario);
            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.FECHACONEXION, new Date((System.currentTimeMillis())));
            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.FECHAULTCONEXION, new Date((System.currentTimeMillis())));

            this.insertRow(rowTSegSesionesVO);
        } else {
            this.setWhereClauseParam(0, idSesion);
            this.executeQuery();
            rowTSegSesionesVO = this.first();
            
            rowTSegSesionesVO.setAttribute(TSegSesionesVORowImpl.FECHAULTCONEXION, new Date((System.currentTimeMillis())));
        }
        
        
    }
}
