package es.ramondin.lanzadoraplicaciones.model.views;

import es.ramondin.lanzadoraplicaciones.model.general.TreeItem;


import java.util.ArrayList;
import java.util.LinkedHashMap;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 01 08:20:04 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegGAFCategoriasVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TSegGAFCategoriasVOImpl() {
    }
    
    public LinkedHashMap<TreeItem, LinkedHashMap<TreeItem, ArrayList<TreeItem>>> getMenuCompleto(Integer idGrupo, String idioma) {
        LinkedHashMap<TreeItem, LinkedHashMap<TreeItem, ArrayList<TreeItem>>> res = new LinkedHashMap<TreeItem, LinkedHashMap<TreeItem, ArrayList<TreeItem>>>();
        LinkedHashMap<TreeItem, ArrayList<TreeItem>> arboles;
        ArrayList<TreeItem> funciones;
        
        this.setIdGrupoBV(idGrupo);
        this.setIdiomaBV(idioma);
        this.executeQuery();
        
        RowSetIterator rsiCategorias = this.getRowSetIterator();
        TSegGAFCategoriasVORowImpl rowCategoria;
        TSegGAFArbolesVORowImpl rowArbol, rowFuncion;
        RowIterator riArboles, riFunciones;
        
        while (rsiCategorias.hasNext()) {
            arboles = null;
            
            rowCategoria = (TSegGAFCategoriasVORowImpl)rsiCategorias.next();
            
            riArboles = rowCategoria.getTSegGAFArboles();
            
            if (riArboles != null) {
                arboles = new LinkedHashMap<TreeItem, ArrayList<TreeItem>>();
                
                while (riArboles.hasNext()) {
                    rowArbol = (TSegGAFArbolesVORowImpl)riArboles.next();
                    funciones = null;
                    
                    riFunciones = rowArbol.getIdFuncionTSegGAFArboles();
                    
                    if (riFunciones != null) {
                        funciones = new ArrayList<TreeItem>();
                        
                        while (riFunciones.hasNext()) {
                            rowFuncion = (TSegGAFArbolesVORowImpl)riFunciones.next();
                            funciones.add(new TreeItem(rowFuncion.getIdFuncion(), rowFuncion.getDenomFuncion(), rowFuncion.getUrl(), rowFuncion.getVersion(), rowFuncion.getNombreTaskFlow(), rowFuncion.getNombreAm()));
                        }
                        
                        if (funciones.isEmpty())
                            funciones = null;
                    }
                    
                    arboles.put(new TreeItem(rowArbol.getIdFuncion(), rowArbol.getDenomFuncion(), rowArbol.getUrl(), rowArbol.getVersion(), rowArbol.getNombreTaskFlow(), rowArbol.getNombreAm()), funciones);
                }
            }   
            
            res.put(new TreeItem(rowCategoria.getIdFuncion(), rowCategoria.getDenomFuncion(), null, null, null, null), arboles);
        }
        
        return res;
    }


    /**
     * Returns the bind variable value for IdGrupoBV.
     * @return bind variable value for IdGrupoBV
     */
    public Integer getIdGrupoBV() {
        return (Integer)getNamedWhereClauseParam("IdGrupoBV");
    }

    /**
     * Sets <code>value</code> for bind variable IdGrupoBV.
     * @param value value to bind as IdGrupoBV
     */
    public void setIdGrupoBV(Integer value) {
        setNamedWhereClauseParam("IdGrupoBV", value);
    }

    /**
     * Returns the bind variable value for IdiomaBV.
     * @return bind variable value for IdiomaBV
     */
    public String getIdiomaBV() {
        return (String)getNamedWhereClauseParam("IdiomaBV");
    }

    /**
     * Sets <code>value</code> for bind variable IdiomaBV.
     * @param value value to bind as IdiomaBV
     */
    public void setIdiomaBV(String value) {
        setNamedWhereClauseParam("IdiomaBV", value);
    }
}
