package es.ramondin.lanzadoraplicaciones.model.views;

import es.ramondin.modelo.seg.entities.TsegsesionesImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 03 11:01:02 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegSesionesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CodUsuario {
            public Object get(TSegSesionesVORowImpl obj) {
                return obj.getCodUsuario();
            }

            public void put(TSegSesionesVORowImpl obj, Object value) {
                obj.setCodUsuario((String)value);
            }
        }
        ,
        FechaConexion {
            public Object get(TSegSesionesVORowImpl obj) {
                return obj.getFechaConexion();
            }

            public void put(TSegSesionesVORowImpl obj, Object value) {
                obj.setFechaConexion((Date)value);
            }
        }
        ,
        FechaUltconexion {
            public Object get(TSegSesionesVORowImpl obj) {
                return obj.getFechaUltconexion();
            }

            public void put(TSegSesionesVORowImpl obj, Object value) {
                obj.setFechaUltconexion((Date)value);
            }
        }
        ,
        IdSesion {
            public Object get(TSegSesionesVORowImpl obj) {
                return obj.getIdSesion();
            }

            public void put(TSegSesionesVORowImpl obj, Object value) {
                obj.setIdSesion((String)value);
            }
        }
        ,
        IdUsuario {
            public Object get(TSegSesionesVORowImpl obj) {
                return obj.getIdUsuario();
            }

            public void put(TSegSesionesVORowImpl obj, Object value) {
                obj.setIdUsuario((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(TSegSesionesVORowImpl object);

        public abstract void put(TSegSesionesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CODUSUARIO = AttributesEnum.CodUsuario.index();
    public static final int FECHACONEXION = AttributesEnum.FechaConexion.index();
    public static final int FECHAULTCONEXION = AttributesEnum.FechaUltconexion.index();
    public static final int IDSESION = AttributesEnum.IdSesion.index();
    public static final int IDUSUARIO = AttributesEnum.IdUsuario.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TSegSesionesVORowImpl() {
    }

    /**
     * Gets TSegSesiones entity object.
     * @return the TSegSesiones
     */
    public TsegsesionesImpl getTSegSesiones() {
        return (TsegsesionesImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for COD_USUARIO using the alias name CodUsuario.
     * @return the COD_USUARIO
     */
    public String getCodUsuario() {
        return (String) getAttributeInternal(CODUSUARIO);
    }

    /**
     * Sets <code>value</code> as attribute value for COD_USUARIO using the alias name CodUsuario.
     * @param value value to set the COD_USUARIO
     */
    public void setCodUsuario(String value) {
        setAttributeInternal(CODUSUARIO, value);
    }

    /**
     * Gets the attribute value for FECHA_CONEXION using the alias name FechaConexion.
     * @return the FECHA_CONEXION
     */
    public Date getFechaConexion() {
        return (Date) getAttributeInternal(FECHACONEXION);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_CONEXION using the alias name FechaConexion.
     * @param value value to set the FECHA_CONEXION
     */
    public void setFechaConexion(Date value) {
        setAttributeInternal(FECHACONEXION, value);
    }

    /**
     * Gets the attribute value for FECHA_ULTCONEXION using the alias name FechaUltconexion.
     * @return the FECHA_ULTCONEXION
     */
    public Date getFechaUltconexion() {
        return (Date) getAttributeInternal(FECHAULTCONEXION);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_ULTCONEXION using the alias name FechaUltconexion.
     * @param value value to set the FECHA_ULTCONEXION
     */
    public void setFechaUltconexion(Date value) {
        setAttributeInternal(FECHAULTCONEXION, value);
    }

    /**
     * Gets the attribute value for ID_SESION using the alias name IdSesion.
     * @return the ID_SESION
     */
    public String getIdSesion() {
        return (String) getAttributeInternal(IDSESION);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SESION using the alias name IdSesion.
     * @param value value to set the ID_SESION
     */
    public void setIdSesion(String value) {
        setAttributeInternal(IDSESION, value);
    }

    /**
     * Gets the attribute value for ID_USUARIO using the alias name IdUsuario.
     * @return the ID_USUARIO
     */
    public BigDecimal getIdUsuario() {
        return (BigDecimal) getAttributeInternal(IDUSUARIO);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_USUARIO using the alias name IdUsuario.
     * @param value value to set the ID_USUARIO
     */
    public void setIdUsuario(BigDecimal value) {
        setAttributeInternal(IDUSUARIO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
