package es.ramondin.lanzadoraplicaciones.model.views;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 07:34:33 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegGAFCategoriasVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdArea {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getIdArea();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setIdArea((Integer)value);
            }
        }
        ,
        Orden {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getOrden();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setOrden((Integer)value);
            }
        }
        ,
        IdGrupo {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getIdGrupo();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setIdGrupo((Integer)value);
            }
        }
        ,
        Idioma {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getIdioma();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setIdioma((String)value);
            }
        }
        ,
        IdFuncion {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getIdFuncion();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setIdFuncion((Integer)value);
            }
        }
        ,
        DenomFuncion {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getDenomFuncion();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setDenomFuncion((String)value);
            }
        }
        ,
        TSegGAFArboles {
            public Object get(TSegGAFCategoriasVORowImpl obj) {
                return obj.getTSegGAFArboles();
            }

            public void put(TSegGAFCategoriasVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(TSegGAFCategoriasVORowImpl object);

        public abstract void put(TSegGAFCategoriasVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDAREA = AttributesEnum.IdArea.index();
    public static final int ORDEN = AttributesEnum.Orden.index();
    public static final int IDGRUPO = AttributesEnum.IdGrupo.index();
    public static final int IDIOMA = AttributesEnum.Idioma.index();
    public static final int IDFUNCION = AttributesEnum.IdFuncion.index();
    public static final int DENOMFUNCION = AttributesEnum.DenomFuncion.index();
    public static final int TSEGGAFARBOLES = AttributesEnum.TSegGAFArboles.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TSegGAFCategoriasVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdArea.
     * @return the IdArea
     */
    public Integer getIdArea() {
        return (Integer) getAttributeInternal(IDAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdArea.
     * @param value value to set the  IdArea
     */
    public void setIdArea(Integer value) {
        setAttributeInternal(IDAREA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Orden.
     * @return the Orden
     */
    public Integer getOrden() {
        return (Integer) getAttributeInternal(ORDEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Orden.
     * @param value value to set the  Orden
     */
    public void setOrden(Integer value) {
        setAttributeInternal(ORDEN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdGrupo.
     * @return the IdGrupo
     */
    public Integer getIdGrupo() {
        return (Integer) getAttributeInternal(IDGRUPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdGrupo.
     * @param value value to set the  IdGrupo
     */
    public void setIdGrupo(Integer value) {
        setAttributeInternal(IDGRUPO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Idioma.
     * @return the Idioma
     */
    public String getIdioma() {
        return (String) getAttributeInternal(IDIOMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Idioma.
     * @param value value to set the  Idioma
     */
    public void setIdioma(String value) {
        setAttributeInternal(IDIOMA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdFuncion.
     * @return the IdFuncion
     */
    public Integer getIdFuncion() {
        return (Integer) getAttributeInternal(IDFUNCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdFuncion.
     * @param value value to set the  IdFuncion
     */
    public void setIdFuncion(Integer value) {
        setAttributeInternal(IDFUNCION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DenomFuncion.
     * @return the DenomFuncion
     */
    public String getDenomFuncion() {
        return (String) getAttributeInternal(DENOMFUNCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DenomFuncion.
     * @param value value to set the  DenomFuncion
     */
    public void setDenomFuncion(String value) {
        setAttributeInternal(DENOMFUNCION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TSegGAFArboles.
     */
    public RowIterator getTSegGAFArboles() {
        return (RowIterator)getAttributeInternal(TSEGGAFARBOLES);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
