package es.ramondin.lanzadoraplicaciones.model.views;

import es.ramondin.lanzadoraplicaciones.model.views.common.TSegUsuarioVO;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 08:21:28 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegUsuarioVOImpl extends ViewObjectImpl implements TSegUsuarioVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TSegUsuarioVOImpl() {
    }
    
    public BigDecimal getIdUsuario(String codUsuario) {
        BigDecimal res = null;
        
        this.setWhereClauseParam(0, codUsuario);
        this.executeQuery();
        
        Row rowTSegUsuarioVO = this.first();
        
        if (rowTSegUsuarioVO != null)
            res = (BigDecimal)rowTSegUsuarioVO.getAttribute(TSegUsuarioVORowImpl.IDUSUARIO);
        
        return res;
    }
    
    public BigDecimal getIdGrupo(String codUsuario) {
        BigDecimal res = null;
        
        this.setWhereClauseParam(0, codUsuario);
        this.executeQuery();
        
        Row rowTSegUsuarioVO = this.first();
        
        if (rowTSegUsuarioVO != null)
            res = (BigDecimal)rowTSegUsuarioVO.getAttribute(TSegUsuarioVORowImpl.IDGRUPO);
        
        return res;
    }
    
    public String getNombreUsuario(String codUsuario) {
        String res = null;
        
        this.setWhereClauseParam(0, codUsuario);
        this.executeQuery();
        
        Row rowTSegUsuarioVO = this.first();
        
        if (rowTSegUsuarioVO != null)
            res = (String)rowTSegUsuarioVO.getAttribute(TSegUsuarioVORowImpl.NOMBREUSUARIO);
        
        return res;
    }
}
