package es.ramondin.lanzadoraplicaciones.model.views;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 31 10:20:49 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TSegGAFArbolesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdArea {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdArea();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setIdArea((Integer)value);
            }
        }
        ,
        Orden {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getOrden();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setOrden((Integer)value);
            }
        }
        ,
        IdGrupo {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdGrupo();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setIdGrupo((Integer)value);
            }
        }
        ,
        Idioma {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdioma();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setIdioma((String)value);
            }
        }
        ,
        IdFuncion {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdFuncion();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setIdFuncion((Integer)value);
            }
        }
        ,
        IdFuncionPadre {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdFuncionPadre();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setIdFuncionPadre((Integer)value);
            }
        }
        ,
        DenomFuncion {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getDenomFuncion();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setDenomFuncion((String)value);
            }
        }
        ,
        Url {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getUrl();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setUrl((String)value);
            }
        }
        ,
        Version {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setVersion((String)value);
            }
        }
        ,
        NombreTaskFlow {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getNombreTaskFlow();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setNombreTaskFlow((String)value);
            }
        }
        ,
        NombreAm {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getNombreAm();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setNombreAm((String)value);
            }
        }
        ,
        IdFuncionTSegGAFArboles {
            public Object get(TSegGAFArbolesVORowImpl obj) {
                return obj.getIdFuncionTSegGAFArboles();
            }

            public void put(TSegGAFArbolesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(TSegGAFArbolesVORowImpl object);

        public abstract void put(TSegGAFArbolesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDAREA = AttributesEnum.IdArea.index();
    public static final int ORDEN = AttributesEnum.Orden.index();
    public static final int IDGRUPO = AttributesEnum.IdGrupo.index();
    public static final int IDIOMA = AttributesEnum.Idioma.index();
    public static final int IDFUNCION = AttributesEnum.IdFuncion.index();
    public static final int IDFUNCIONPADRE = AttributesEnum.IdFuncionPadre.index();
    public static final int DENOMFUNCION = AttributesEnum.DenomFuncion.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int NOMBRETASKFLOW = AttributesEnum.NombreTaskFlow.index();
    public static final int NOMBREAM = AttributesEnum.NombreAm.index();
    public static final int IDFUNCIONTSEGGAFARBOLES = AttributesEnum.IdFuncionTSegGAFArboles.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TSegGAFArbolesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdArea.
     * @return the IdArea
     */
    public Integer getIdArea() {
        return (Integer) getAttributeInternal(IDAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdArea.
     * @param value value to set the  IdArea
     */
    public void setIdArea(Integer value) {
        setAttributeInternal(IDAREA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Orden.
     * @return the Orden
     */
    public Integer getOrden() {
        return (Integer) getAttributeInternal(ORDEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Orden.
     * @param value value to set the  Orden
     */
    public void setOrden(Integer value) {
        setAttributeInternal(ORDEN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdGrupo.
     * @return the IdGrupo
     */
    public Integer getIdGrupo() {
        return (Integer) getAttributeInternal(IDGRUPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdGrupo.
     * @param value value to set the  IdGrupo
     */
    public void setIdGrupo(Integer value) {
        setAttributeInternal(IDGRUPO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Idioma.
     * @return the Idioma
     */
    public String getIdioma() {
        return (String) getAttributeInternal(IDIOMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Idioma.
     * @param value value to set the  Idioma
     */
    public void setIdioma(String value) {
        setAttributeInternal(IDIOMA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdFuncion.
     * @return the IdFuncion
     */
    public Integer getIdFuncion() {
        return (Integer) getAttributeInternal(IDFUNCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdFuncion.
     * @param value value to set the  IdFuncion
     */
    public void setIdFuncion(Integer value) {
        setAttributeInternal(IDFUNCION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdFuncionPadre.
     * @return the IdFuncionPadre
     */
    public Integer getIdFuncionPadre() {
        return (Integer) getAttributeInternal(IDFUNCIONPADRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdFuncionPadre.
     * @param value value to set the  IdFuncionPadre
     */
    public void setIdFuncionPadre(Integer value) {
        setAttributeInternal(IDFUNCIONPADRE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DenomFuncion.
     * @return the DenomFuncion
     */
    public String getDenomFuncion() {
        return (String) getAttributeInternal(DENOMFUNCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DenomFuncion.
     * @param value value to set the  DenomFuncion
     */
    public void setDenomFuncion(String value) {
        setAttributeInternal(DENOMFUNCION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Url.
     * @return the Url
     */
    public String getUrl() {
        return (String) getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Url.
     * @param value value to set the  Url
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public String getVersion() {
        return (String) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Version.
     * @param value value to set the  Version
     */
    public void setVersion(String value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NombreTaskFlow.
     * @return the NombreTaskFlow
     */
    public String getNombreTaskFlow() {
        return (String) getAttributeInternal(NOMBRETASKFLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NombreTaskFlow.
     * @param value value to set the  NombreTaskFlow
     */
    public void setNombreTaskFlow(String value) {
        setAttributeInternal(NOMBRETASKFLOW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NombreAm.
     * @return the NombreAm
     */
    public String getNombreAm() {
        return (String) getAttributeInternal(NOMBREAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NombreAm.
     * @param value value to set the  NombreAm
     */
    public void setNombreAm(String value) {
        setAttributeInternal(NOMBREAM, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link IdFuncionTSegGAFArboles.
     */
    public RowIterator getIdFuncionTSegGAFArboles() {
        return (RowIterator)getAttributeInternal(IDFUNCIONTSEGGAFARBOLES);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
